name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Buildozer and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev unzip
          pip install --upgrade pip --no-cache-dir
          pip install buildozer[github] cython --no-cache-dir
      
      - name: Configure buildozer.spec
        run: |
          sed -i 's/#p4a.branch = master/p4a.branch = develop/g' buildozer.spec
          sed -i 's/p4a.branch = main/p4a.branch = develop/g' buildozer.spec
          sed -i 's/#android.api = 33/android.api = 33/g' buildozer.spec
          sed -i 's/#android.build_tools_version =.*/android.build_tools_version = 34.0.0/g' buildozer.spec
          sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec

      - name: Delete old buildozer cache
        run: rm -rf ./.buildozer
      
      - name: Manual Android SDK Setup
        id: android_setup
        run: |
          # Create SDK and NDK directories
          mkdir -p .buildozer/android/platform/android-sdk
          mkdir -p .buildozer/android/platform/android-ndk
          
          # Download Android command-line tools directly
          cd .buildozer/android/platform/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          
          # Accept licenses explicitly using sdkmanager (corrected path)
          yes | cmdline-tools/bin/sdkmanager --licenses || true
          
          # Install specific build tools and platforms (corrected path)
          cmdline-tools/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-33"

          # Add SDK and NDK paths directly to the buildozer.spec
          SDK_PATH="$(pwd)"
          NDK_PATH="$(pwd)/../android-ndk"
          echo "android.sdk_path = ${SDK_PATH}" >> ../../../../buildozer.spec
          echo "android.ndk_path = ${NDK_PATH}" >> ../../../../buildozer.spec

      - name: Build the APK
        run: buildozer -v android debug
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
