name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev unzip
          pip install --upgrade pip --no-cache-dir
          pip install buildozer[github] cython --no-cache-dir
          # Fix for outdated buildozer behavior with develop branch
          sed -i 's/#p4a.branch = master/p4a.branch = develop/g' buildozer.spec
          sed -i 's/p4a.branch = main/p4a.branch = develop/g' buildozer.spec
          sed -i 's/#android.api = 31/android.api = 33/g' buildozer.spec
          sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
          sed -i 's/#android.build_tools_version =.*/android.build_tools_version = 34.0.0/g' buildozer.spec

      # The 'buildozer appclean' step is removed to avoid the FileNotFoundError.
      # The 'android debug' command will handle the initial setup automatically.

      - name: Build the APK
        run: |
          # Buildozer will download python-for-android and other SDK components as needed.
          buildozer -v android debug
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
