name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'kivy/buildozer:latest'
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build the APK
        run: |
          buildozer -v android debug deploy run logcat > app_crash.log 2>&1

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-crash-log
          path: app_crash.log
