name: Android Release Buildozer
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build with Buildozer for Android Release
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer-cmd: "buildozer android release"
          python-version: "3.9"
          
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-key.keystore
      
      - name: Sign Android Release
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: bin
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
